# Generated by Django 5.0.6 on 2024-07-07 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('admin_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('api_id', models.IntegerField(unique=True)),
                ('api_hash', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=13)),
                ('telegram_user_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
                'db_table': 'admins',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('user_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='TelegramGroups',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('group_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_api.admins')),
            ],
            options={
                'verbose_name': 'Telegram Group',
                'verbose_name_plural': 'Telegram Groups',
                'db_table': 'telegram_groups',
            },
        ),
    ]
