# Generated by Django 5.0.6 on 2024-07-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_api', '0002_alter_telegramgroups_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramgroups',
            name='id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telegramgroups',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
