# Generated by Django 5.0.6 on 2024-07-08 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_api', '0003_telegramgroups_id_alter_telegramgroups_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramgroups',
            old_name='id',
            new_name='telegram_chat_id',
        ),
    ]
